name: main test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt install curl wget gcc-arm-none-eabi gcc make; mkdir ~/temp
    - name: compile activeon dx
      run: cd src; make init font ahdk p=activeondx d=~/temp
